#!/usr/bin/env php
<?php
require __DIR__ . '../../../../wp-config.php';

use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new ControllerCommand());

$application->run();